# Required by Atom feed template
title = "Flott - Motion Control in Rust"

base_url = "https://flott-motion.org"

compile_sass       = true
generate_feed      = true
build_search_index = true

[markdown]
highlight_code = true

[extra.authors.hannobraun]
name = "Hanno Braun"
link = "https://github.com/hannobraun"
